version: '3.8'
services:
  fe-app:
    image: registry.cn-hangzhou.aliyuncs.com/back_lgh/meeting_room_booking:02
    ports:
      - 50:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/lgh/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: leilei111
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/lgh/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
